---
- hosts: all
  become: yes
  tasks:
  - name: install
    yum: 
      name: "{{ item }}"
      state: installed
    with_items:
    - epel-release
    - gcc
    - make
    - strace
    - sysstat
    - lsof
    - tcpdump
    - wireshark
    - telnet
    - nc
    - traceroute
    - git
    - tmux
    - bash-completion
    - bind
    - libselinux-python
    - postfix
    - pypolicyd-spf
    - opendkim
    - opendmarc
    - dovecot

  - selinux: state=disabled

  - name: skel Maildir
    file:
      path: "/etc/skel/Maildir/{{ item }}"
      state: directory
      mode: 0700
    with_items:
    - new
    - cur
    - tmp

  - name: ssh ssh_config
    copy:
      src: files/ssh/ssh_config
      dest: /etc/ssh/ssh_config
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: resolv.conf
    copy:
      src: files/resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: postfix main.cf
    copy:
      src: files/postfix/main.cf
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: opendkim
    copy:
      src: files/opendkim/opendkim.conf
      dest: /etc/opendkim.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: opendmarc
    copy:
      src: files/opendmarc/opendmarc.conf
      dest: /etc/opendmarc.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: dovecot user
    copy:
      src: files/dovecot/users
      dest: /etc/dovecot/users
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: dovecot conf.d
    copy:
      src: "files/dovecot/conf.d/{{ item }}"
      dest: /etc/dovecot/conf.d
      owner: root
      group: root
      mode: 0644
      backup: yes
    with_items:
    - 10-auth.conf
    - 10-mail.conf

  - service:
      name: "{{ item }}"
      state: restarted
    with_items:
    - sshd
    - named
    - postfix
    - dovecot
    - opendkim
    - opendmarc
