---
- hosts: all
  become: yes
  tasks:
  - name: install
    yum: 
      name: "{{ item }}"
      state: installed
    with_items:
    - epel-release
    - gcc
    - make
    - strace
    - sysstat
    - lsof
    - tcpdump
    - wireshark
    - telnet
    - nc
    - traceroute
    - postfix
    - git
    - tmux
    - bash-completion
    - libselinux-python
    - pypolicyd-spf
    - opendkim
    - opendmarc
    - dovecot

  - name: skel Maildir
    file:
      path: "/etc/skel/Maildir/{{ item }}"
      state: directory
      mode: 0700
    with_items:
    - new
    - cur
    - tmp

  - name: put main.cf
    copy:
      src: files/main.cf
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: 0644
      backup: yes
